[package]
name = "localmt-models"
edition.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true
version.workspace = true

[dependencies]
localmt-core = { path = "../localmt-core" }
serde.workspace = true
serde_json.workspace = true
sha2.workspace = true

[lints]
workspace = true
