[package]
name = "localmt-tokenizer"
edition.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true
version.workspace = true

[dependencies]
localmt-core = { path = "../localmt-core" }
localmt-models = { path = "../localmt-models" }
tokenizers = { version = "0.21.4", optional = true, default-features = false, features = [
    "fancy-regex",
] }

[features]
default = []
hf-tokenizers = ["dep:tokenizers"]

[lints]
workspace = true
