[package]
name = "localmt-tokenizer"
edition.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true
version.workspace = true

[dependencies]
localmt-core = { path = "../localmt-core" }
localmt-models = { path = "../localmt-models" }

[lints]
workspace = true
