[package]
name = "localmt-ffi"
edition.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true
version.workspace = true

[lib]
crate-type = ["cdylib", "staticlib", "rlib"]

[dependencies]
localmt = { path = "../localmt" }

[features]
default = []
hf-tokenizers = ["localmt/hf-tokenizers"]
llama-runtime = ["localmt/llama-runtime"]
ort-runtime = ["localmt/ort-runtime"]

[lints.rust]
unsafe_code = "allow"

[lints.clippy]
expect_used = "deny"
panic = "deny"
todo = "deny"
unimplemented = "deny"
unwrap_used = "deny"
