[package]
name = "localmt"
edition.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true
version.workspace = true

[dependencies]
localmt-bench = { path = "../localmt-bench" }
localmt-core = { path = "../localmt-core" }
localmt-engine = { path = "../localmt-engine" }
localmt-engine-ort = { path = "../localmt-engine-ort" }
localmt-models = { path = "../localmt-models" }

[features]
default = []
ort-runtime = ["localmt-engine-ort/ort-runtime"]

[lints]
workspace = true
