[package]
name = "localmt-cli"
edition.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true
version.workspace = true

[[bin]]
name = "localmt"
path = "src/main.rs"
doc = false

[dependencies]
localmt = { path = "../localmt" }
localmt-bench = { path = "../localmt-bench" }
localmt-models = { path = "../localmt-models" }

[lints]
workspace = true
